### ISSUE TITLE
example phpmyadmin doesn't work as expected

### ISSUE THREAD

**Issue by bkircher67** [docbuc/dockerbuch#2]
Hello,

the example for the communication on the internal network doesn't work as expected Page 47). When I try to logon in phpmyadmin I get the error message:

> Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.

But starting the example with HTTPS doesn't work at all.

KR Bernd

**Comment by beoe** [comment]
Hi,
very sorry to answer so late, but I forgot to check this github-account for issues.

You are absolutely right, that the commands listed on page 46 do not work as expected. The problem with these commands is, that mariadb won't start without a root password, or an environment variable telling mariadb that it is OK to run with an empty root password. This can be seen after starting mariadb with the command:
```
$ docker run -d --name mariadb-test5 --network test-net \
    -v /home/<username>/varlibmysql/:/var/lib/mysql mariadb

  621b0835d56c72e58ad6354c084cc695f0a70e131ac3b5bd1e7f1ceb717c1696

$ docker logs mariadb-test5

  error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

So with setting `MYSQL_ALLOW_EMPTY_PASSWORD` to `true` mariadb will start correctly and phpmyadmin will connect (use user `root` with an empty password to login on <http://localhost:8080>):

```
docker run -d --name mariadb-test5 --network test-net \
  -v /home/<username>/varlibmysql/:/var/lib/mysql \
  -e MYSQL_ALLOW_EMPTY_PASSWORD=true mariadb
```

**Comment by MichaelKofler** [comment]
Sorry for answering even later. 

The example on page 46 was never planned to work without a password. Instead, the example begins on page 43, where mariadb-test2 is initialized with a password. The password is part of the database files stored in /home/user/varlibmysql and is reused in the following examples (mariadb-test3, -test4 and test5).

I will clarify the text accordingly for the next edition of the book.

Thanks for your feedback,

   Michael
